# LIST OF REQUIRED PACKAGES -----------------------------------------------
library(data.table)
library(DT)
library(ggplot2)
library(fastqq)
library(kit)
library(shiny)
library(shinyBS)
library(shinycssloaders)
library(shinydashboard)
library(shinyjs)
library(fastqq)
